routes/web.php
<?php

use App\Models\IssuePackage;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StockController;
use App\Http\Controllers\Admin\CityController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\DonarController;
use App\Http\Controllers\IssuePackageController;
use App\Http\Controllers\Admin\DpersonController;
use App\Http\Controllers\Admin\PackageController;
use App\Http\Controllers\Admin\InventoryController;
use App\Http\Controllers\Admin\AssignPackageController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/login', function () {
    return view('auth.login');
})->name('login');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Auth::routes();

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::middleware(['auth',])->group(function () {



        //Admin Routes
        Route::get('dashboard', [AdminController::class, 'AdminDashboard']);

        //DRP's Routes
        Route::get('dperson', [DpersonController::class, 'index']);
        Route::get('add/person', [DpersonController::class, 'create']);
        Route::post('store/person', [DpersonController::class, 'store']);
        Route::get('edit/person/{id}', [DpersonController::class, 'edit']);
        Route::put('update/person/{id}', [DpersonController::class, 'update']);
        Route::get('delete/person/{id}', [DpersonController::class, 'destroy']);

        // Packages routes

        Route::get('package', [PackageController::class, 'index']);
        Route::get('add/package', [PackageController::class, 'create']);
        Route::post('store/package', [PackageController::class, 'store']);
        Route::get('edit/package/{id}', [PackageController::class, 'edit']);
        Route::put('update/package/{id}', [PackageController::class, 'update']);
        Route::get('delete/package/{id}', [PackageController::class, 'destroy']);

        // inventory routes

        Route::resource('product', InventoryController::class);
        Route::get('inventory-report', [InventoryController::class,'inventory_report'])->name('product.inventory_report');

        // Donar routes

        Route::resource('donar', DonarController::class);
        Route::resource('user', DonarController::class);
        Route::get('delete-user/{id}', [DonarController::class,'destroy']);
        Route::get('delete-donor/{id}', [DonarController::class,'destroyDonor']);
        Route::get('donar-history/{id}', [DonarController::class,'donorHistory']);

        Route::post('store-donor', [DonarController::class,'storeDonor']);
        Route::get('donor-list', [DonarController::class,'donorall']);
        Route::get('donor-create', [DonarController::class,'createDonor']);
        Route::get('donor-edit/{id}', [DonarController::class,'editDonor']);
        Route::put('donar-update/{id}', [DonarController::class,'updateDonor']);
        Route::get('donar-history/{id}', [DonarController::class,'donorHistory']);
        Route::post('new-donation', [DonarController::class,'newDonation']);

       // cities route
       Route::get('/get-cities/{state}', [CityController::class, 'getCities']);
       // Roles
        Route::resource('role', RoleController::class);

        // Stock Management
        Route::resource('stock', StockController::class);



        // Assign packages
        Route::get('all-assign-package', [PackageController::class, 'allAssignPackage']);
        Route::post('assign-package', [PackageController::class, 'assignPackageNow']);
        Route::get('assign-package', [PackageController::class, 'assignPackage']);
        Route::get('get-package-detail', [PackageController::class, 'PackageDetails']);
        Route::get('edit-package-detail/{id}', [PackageController::class, 'editPackageDetails']);
        Route::get('edit-assign-package/{id}', [PackageController::class, 'editAssignPackage']);
        Route::put('update-assigned-package/{id}', [PackageController::class, 'updatePackageDetails']);
        Route::get('delete-assigned-package/{id}', [PackageController::class, 'destroyAssignedPackage']);

        // Issue Package
        Route::get('issue-package', [IssuePackageController::class, 'index']);
        Route::post('issue-now', [IssuePackageController::class, 'store']);
        Route::get('search-issue-people', [IssuePackageController::class, 'create']);
        Route::post('search-issue-people', [IssuePackageController::class, 'searchDPeople']);
        Route::get('issue-packages-report', [IssuePackageController::class, 'issuePackageReport']);
        Route::get('issued-package/{id}', [IssuePackageController::class, 'issuedPackage']);

        // Route::get('get-issuepkg/{slug}', IssuePackageController::class, 'getIssuePkg');

    });
            //Is Admin Middleware
    Route::middleware(['auth','isAdmin'])->group(function () {

        //UserListing
        Route::get('userlist',[AdminController::class, 'UsersListing']);
        Route::patch('updateStatus',[ AdminController::class,'updateUserStatus'])->name('userlist.updateUserstatus');
        Route::get('userlist/destroy/{id}',[AdminController::class, 'destroy']);

    });


});

app/Http/Controllers/Admin/RoleController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Spatie\Permission\Models\Permission;
use Spatie\Permission\Models\Role;

class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $roles = Role::all();
        return view('admin.roles.index',compact('roles'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $role = Role::where('id',$id)->first();
        $permissions = Permission::get();
        $rolePermissions = DB::table("role_has_permissions")->where("role_has_permissions.role_id",$id)
            ->pluck('role_has_permissions.permission_id','role_has_permissions.permission_id')
            ->all();

        return view('admin.roles.edit',compact('role','rolePermissions','permissions'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        // dd($request, $id);
        $role = Role::find($id);
        $role->name = $request->name;
        $role->save();

        $role->syncPermissions($request->input('permission'));

        return redirect(route('admin.role.index'))->with('success','Role updated successfully');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
}

resources/views/admin/roles/edit.blade.php
@extends('layouts.admin')
<style>
    .container {
        margin-top: 80px;
        margin-left: 20%;
        /* margin-left: 10%; */
    }

    .col-md-10 {
        margin-left: 10%;
    }
</style>
@section('content')
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
    <!--page-wrapper-->
    <div class="page-wrapper">
        <!--page-content-wrapper-->
        <div class="page-content-wrapper">
            <div class="page-content">
                <!--breadcrumb-->
                <div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
                    <div class="breadcrumb-title pe-3">Edit Role</div>
                    
                    <div class="ms-auto">
                        <div class="btn-group">
                            <a href="{{ route('admin.donar.index') }}" class="btn btn-primary">Back</a>
                        </div>
                    </div>
                </div>
                <!--end breadcrumb-->
                <div class="row bg-white">
                    <form action="{{ route('admin.role.update', $role->id) }}" method="POST">
                        @csrf
                        @method('put')
                        <div class="row">
                            <div class="col-xs- col-sm-6 col-md-6 mt-2">
                                <strong>Name:</strong>
                                <input type="text" name="name" id="name" value="{{ $role->name }}"
                                    class="form-control" />
                            </div>
                            <div class="col-md-12">
                                <strong>Permissions:</strong>
                                <select id="permission" name="permission[]" class="form-control" multiple="">
                                    @foreach ($permissions as $value)
                                        <option value="{{ $value->id }}"
                                            {{ in_array($value->id, $rolePermissions) ? 'selected' : '' }}>
                                            {{ $value->name }}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>

                        <div class=" col-sm-12 col-md-12 text-end">
                            <button type="submit" class="btn btn-primary mt-2">Update</button>
                        </div>

                </div>
                </form>
            </div>
            <!--end row-->
        </div>
    </div>
    <!--end page-content-wrapper-->
    </div>
    <!--end page-wrapper-->
@endsection
@push('scripts')
<script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

    <script>
        $(document).ready(function() {
            $('#permission').select2();
        });
    </script>
@endpush

resources/views/admin/roles/index.blade.php
@extends('layouts.admin')

@section('content')
    <style>
        .card {
            margin-top: 80px;
            margin: 10px;
        }
    </style>
    <!--page-wrapper-->
    <div class="page-wrapper">
        <!--page-content-wrapper-->
        <div class="page-content-wrapper">
            <div class="col-md-12">
                @if (session('message'))
                    <div class="alert alert-success">{{ session('message') }}</div>
                @endif
                <div class="card">
                    <div class="card-header">
                        <h3>Roles</h3>
                        {{-- <a href="{{ url('admin.role.create') }}" class="btn btn-primary btn-sm float-end">Add Donor</a> --}}
                    </div>

                    <div class="card-body">
                    <div class="table-responsive">
							<table id="example2" class="table table-striped table-bordered" style="width:100%">
								
                            <thead>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Action</th>
                            </thead>

                            <tbody>

                                @forelse ($roles as $role)
                                    <tr>
                                        <td>{{ $role->id }}</td>
                                        <td>{{ $role->name }}</td>
                                        <td>
                                            <a href="{{ route('admin.role.edit', $role->id) }}"
                                                class="btn btn-primary btn-sm">Edit</a>
                                        </td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="5">No Donar Found</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div> </div>
                </div>
            </div>
        </div>
    </div>
@endsection