routes/web.php
<?php

use App\Models\IssuePackage;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StockController;
use App\Http\Controllers\Admin\CityController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\DonarController;
use App\Http\Controllers\IssuePackageController;
use App\Http\Controllers\Admin\DpersonController;
use App\Http\Controllers\Admin\PackageController;
use App\Http\Controllers\Admin\InventoryController;
use App\Http\Controllers\Admin\AssignPackageController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/login', function () {
    return view('auth.login');
})->name('login');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Auth::routes();

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::middleware(['auth',])->group(function () {



        //Admin Routes
        Route::get('dashboard', [AdminController::class, 'AdminDashboard']);

        //DRP's Routes
        Route::get('dperson', [DpersonController::class, 'index']);
        Route::get('add/person', [DpersonController::class, 'create']);
        Route::post('store/person', [DpersonController::class, 'store']);
        Route::get('edit/person/{id}', [DpersonController::class, 'edit']);
        Route::put('update/person/{id}', [DpersonController::class, 'update']);
        Route::get('delete/person/{id}', [DpersonController::class, 'destroy']);

        // Packages routes

        Route::get('package', [PackageController::class, 'index']);
        Route::get('add/package', [PackageController::class, 'create']);
        Route::post('store/package', [PackageController::class, 'store']);
        Route::get('edit/package/{id}', [PackageController::class, 'edit']);
        Route::put('update/package/{id}', [PackageController::class, 'update']);
        Route::get('delete/package/{id}', [PackageController::class, 'destroy']);

        // inventory routes

        Route::resource('product', InventoryController::class);
        Route::get('inventory-report', [InventoryController::class,'inventory_report'])->name('product.inventory_report');

        // Donar routes

        Route::resource('donar', DonarController::class);
        Route::resource('user', DonarController::class);
        Route::get('delete-user/{id}', [DonarController::class,'destroy']);
        Route::get('delete-donor/{id}', [DonarController::class,'destroyDonor']);
        Route::get('donar-history/{id}', [DonarController::class,'donorHistory']);

        Route::post('store-donor', [DonarController::class,'storeDonor']);
        Route::get('donor-list', [DonarController::class,'donorall']);
        Route::get('donor-create', [DonarController::class,'createDonor']);
        Route::get('donor-edit/{id}', [DonarController::class,'editDonor']);
        Route::put('donar-update/{id}', [DonarController::class,'updateDonor']);
        Route::get('donar-history/{id}', [DonarController::class,'donorHistory']);
        Route::post('new-donation', [DonarController::class,'newDonation']);

       // cities route
       Route::get('/get-cities/{state}', [CityController::class, 'getCities']);
       // Roles
        Route::resource('role', RoleController::class);

        // Stock Management
        Route::resource('stock', StockController::class);



        // Assign packages
        Route::get('all-assign-package', [PackageController::class, 'allAssignPackage']);
        Route::post('assign-package', [PackageController::class, 'assignPackageNow']);
        Route::get('assign-package', [PackageController::class, 'assignPackage']);
        Route::get('get-package-detail', [PackageController::class, 'PackageDetails']);
        Route::get('edit-package-detail/{id}', [PackageController::class, 'editPackageDetails']);
        Route::get('edit-assign-package/{id}', [PackageController::class, 'editAssignPackage']);
        Route::put('update-assigned-package/{id}', [PackageController::class, 'updatePackageDetails']);
        Route::get('delete-assigned-package/{id}', [PackageController::class, 'destroyAssignedPackage']);

        // Issue Package
        Route::get('issue-package', [IssuePackageController::class, 'index']);
        Route::post('issue-now', [IssuePackageController::class, 'store']);
        Route::get('search-issue-people', [IssuePackageController::class, 'create']);
        Route::post('search-issue-people', [IssuePackageController::class, 'searchDPeople']);
        Route::get('issue-packages-report', [IssuePackageController::class, 'issuePackageReport']);
        Route::get('issued-package/{id}', [IssuePackageController::class, 'issuedPackage']);

        // Route::get('get-issuepkg/{slug}', IssuePackageController::class, 'getIssuePkg');

    });
            //Is Admin Middleware
    Route::middleware(['auth','isAdmin'])->group(function () {

        //UserListing
        Route::get('userlist',[AdminController::class, 'UsersListing']);
        Route::patch('updateStatus',[ AdminController::class,'updateUserStatus'])->name('userlist.updateUserstatus');
        Route::get('userlist/destroy/{id}',[AdminController::class, 'destroy']);

    });


});

resources/views/layouts/inc/admin/flash_messages.blade.php
@if ($message = Session::get('success'))
    <!-- <div class="alert alert-success">
  <p></p>
</div> -->
    <script>
        Toast.fire({
            icon: 'success',
            title: "{{ $message }}",
        })
    </script>
@endif
@if ($message = Session::get('message'))
    <!-- <div class="alert alert-success">
  <p></p>
</div> -->
    <script>
        Toast.fire({
            icon: 'success',
            title: "{{ $message }}",
        })
    </script>
@endif

@if ($message = Session::get('error'))
    <!-- <div class="alert alert-danger">
  <p>{{ $message }}</p>
</div> -->
    <script>
        Toast.fire({
            icon: 'error',
            title: "{{ $message }}",
        })
    </script>
@endif
@if ($message = Session::get('middleware-error'))
    <!-- <div class="alert alert-warning">
  <p>{{ $message }}</p>
</div> -->
    <script>
        Toast.fire({
            icon: 'warning',
            title: "{{ $message }}",
        })
    </script>
@endif

@if ($errors->any())
    {{-- {{dd($errors)}} --}}
    {{-- <div class="alert alert-danger">
        <ul> --}}
             @foreach ($errors->all() as $error)
                 {{-- <li>{{ $error }}</li> --}}
                <script>
                Toast.fire({
                icon: 'error',
                title: "{{ $error }}",
                })
                </script>

                @break
            @endforeach
        {{-- </ul>
    </div> --}}
@endif

@push('scripts')
<script type="text/javascript">
    $("document").ready(function() {
        setTimeout(function() {
            $("div.alert").remove();
        }, 3500); // 5 secs

    });
</script>
@endpush
@push('script')
<script type="text/javascript">
    $("document").ready(function() {
        setTimeout(function() {
            $("div.alert").remove();
        }, 3500); // 3.5 secs

    });
</script>
@endpush

resources/views/layouts/inc/admin/footer.blade.php
<!--footer -->
<div class="footer">
    <p class="mb-0">Rashan @2023 | Developed By : <a href="https://www.linkedin.com/in/naseeb-ul-hassan-8b682b136/" target="_blank">Naseeb ul Hassan</a>
    </p>
</div>
<!-- end footer -->

resources/views/layouts/inc/admin/header.blade.php
<?php
session_start();
?>
<header class="top-header">
    <nav class="navbar navbar-expand">
        <div class="left-topbar d-flex align-items-center">
            <a href="javascript:;" class="toggle-btn"> <i class="bx bx-menu"></i>
            </a>
        </div>
        <div class="right-topbar ms-auto">
            <ul class="navbar-nav">
                <li class="nav-item search-btn-mobile">
                 
                </li>
                <li class="nav-item dropdown dropdown-user-profile">
                    <a class="nav-link dropdown-toggle dropdown-toggle-nocaret" href=""
                        data-bs-toggle="dropdown">
                        <div class="d-flex user-box align-items-center">
                            <div class="user-info">
                              

                            </div>
                            <img src="../assets/images/avatars/avatar-1.png" class="user-img" alt="user avatar">
                        </div>
                        
                    </a>
                    <div class="dropdown-menu dropdown-menu-end">
                        <a class="dropdown-item" href="javascript:;"><i class="bx bx-user"></i><span>Profile</span></a>
                        {{ Auth::user()->name }}
                        <div class="dropdown-divider mb-0"><i class="bx bx-user"></i></div>
                        
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                onclick="event.preventDefault();
                                            document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>
                            <form id="logout-form" action="{{ route('logout') }}" method="POST" class="d-none">
                                @csrf
                            </form>
                        
                    </div>
                </li>

            </ul>
        </div>
    </nav>
</header>

resources/views/layouts/inc/admin/sidebar.blade.php
<!--sidebar-wrapper-->
<div class="sidebar-wrapper" data-simplebar="true">
    <div class="sidebar-header">
        <div class="">
            <img src="../assets/images/logo-icon.png" class="logo-icon-2" alt="" />
        </div>
        <div>
            <h4 class="logo-text">Khidmat-e-Khalaq</h4>
        </div>
        <a href="javascript:;" class="toggle-btn ms-auto"> <i class="bx bx-menu"></i>
        </a>
    </div>
    <!--navigation-->
    <ul class="metismenu" id="menu">
        @can('dashboard')
            <li>
                <a href="{{ url('admin/dashboard') }}">
                    <div class="parent-icon icon-color-1"><i class="bx bx-home-alt"></i>
                    </div>
                    <div class="menu-title">Dashboard</div>
                </a>

            </li>
        @endcan
        <li>
            <a class="has-arrow" href="javascript:;">
                <div class="parent-icon icon-color-10"><i class="bx bx-user"></i>
                </div>
                <div class="menu-title">Users / Donors </div>
            </a>
            <ul>



        @can('users')
            <li>
                <a href="{{ route('admin.donar.index') }}">
                    <div class="parent-icon icon-color-2"><i class="bx bx-user-circle"></i>
                    </div>
                    <div class="menu-title">Users List</div>
                </a>
            </li>
        @endcan
        @can('donor')
            <li>
                <a href="{{ url('admin/donor-list') }}">
                    <div class="parent-icon icon-color-2"> <i class="bx bx-donate-blood"></i>
                    </div>
                    <div class="menu-title">Donors</div>
                </a>
            </li>
        @endcan
        @can('user-for-approvel')
            <li>
                <a href="{{ url('admin/userlist') }}">
                    <div class="parent-icon icon-color-2"> <i class="bx bx-user"></i>
                    </div>
                    <div class="menu-title">Activate / Deactivate Users</div>
                </a>
            </li>
        @endcan

        </ul>
    </li>
          <li>
            <a class="has-arrow" href="javascript:;">
                <div class="parent-icon icon-color-10"><i class="bx bx-store alt icon"></i>
                </div>
                <div class="menu-title">Inventory Details</div>
            </a>
            <ul>
                @can('inventory')
                <li>
                    <a href="{{ route('admin.product.index') }}">
                        <div class="parent-icon icon-color-3"><i class="bx bx-folder"></i>
                        </div>
                        <div class="menu-title">Add Inventory</div>
                    </a>
                </li>
                @endcan
                @can('inventory-history')
                <li>
                    <a href="{{ route('admin.product.inventory_report') }}">
                        <div class="parent-icon icon-color-3"><i class="bx bx-file"></i>
                        </div>
                        <div class="menu-title">Inventory Report</div>
                    </a>
                </li>
                @endcan
                 {{-- @can('inventory-stock-history') --}}
                    <li>
                        <a href="{{ route('admin.stock.index') }}">
                            <div class="parent-icon icon-color-3"><i class="bx bx-file"></i>
                            </div>
                            <div class="menu-title">Inventory Stock History</div>
                        </a>
                    </li>
                {{-- @endcan --}}
            </ul>
    </li>
  <li>
    <a class="has-arrow" href="javascript:;">
        <div class="parent-icon icon-color-10"><i class="bx bx-grid-alt"></i>
        </div>
        <div class="menu-title">Deserving Person</div>
    </a>
    <ul>

        @can('package')
            <li>
                <a href="{{ url('admin/package') }}">
                    <div class="parent-icon icon-color-2"><i class="bx bx-archive"></i>
                    </div>
                    <div class="menu-title">Create Packages</div>
                </a>
            </li>
        @endcan
        @can('people')
            <li>
                <a href="{{ url('admin/dperson') }}">
                    <div class="parent-icon icon-color-2"><i class="bx bx-group"></i>
                    </div>
                    <div class="menu-title">Add Person</div>
                </a>
            </li>
        @endcan

        @can('assign-package')
            <li>
                <a href="{{ url('admin/all-assign-package') }}">
                    <div class="parent-icon icon-color-3"> <i class="bx bx-repeat"></i>
                    </div>
                    <div class="menu-title">Assign Packages</div>
                </a>
            </li>
        @endcan

        @can('issue-package')
            <li>
                <a href="{{ url('admin/issue-package') }}">
                    <div class="parent-icon icon-color-3"> <i class="bx bx-task"></i>
                    </div>
                    <div class="menu-title">Issue Packages</div>
                </a>
            </li>
        @endcan

        </ul>
</li>
<li>
    <a class="has-arrow" href="javascript:;">
        <div class="parent-icon icon-color-10"><i class="bx bx-line-chart"></i>
        </div>
        <div class="menu-title">Reports</div>
    </a>
    <ul>

            <li>
                <a href="{{ url('admin/issue-packages-report') }}">
                    <div class="parent-icon icon-color-3"> <i class="bx bx-file"></i>
                    </div>
                    <div class="menu-title">Issued Packages Report</div>
                </a>
            </li>

            </ul>
    </li>
    <li>
        <a class="has-arrow" href="javascript:;">
            <div class="parent-icon icon-color-10"><i class="bx bx-cog"></i>
            </div>
            <div class="menu-title">Settings</div>
        </a>
        <ul>
        @can('roles')
            <li>
                <a href="{{ route('admin.role.index') }}">
                    <div class="parent-icon icon-color-3"> <i class='bx bx-plug me-2'></i>
                    </div>
                    <div class="menu-title">Roles</div>
                </a>
            </li>
        @endcan
        </ul>
    </li>

    </ul>
    <!--end navigation-->
</div>
<!--end sidebar-wrapper-->

resources/views/layouts/inc/admin/switcher.blade.php
<!--start switcher-->
<div class="switcher-body">
	<button class="btn btn-primary btn-switcher shadow-sm" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasScrolling" aria-controls="offcanvasScrolling"><i class="bx bx-cog bx-spin"></i></button>
	<div class="offcanvas offcanvas-end shadow border-start-0 p-2" data-bs-scroll="true" data-bs-backdrop="false" tabindex="-1" id="offcanvasScrolling">
		<div class="offcanvas-header border-bottom">
			<h5 class="offcanvas-title" id="offcanvasScrollingLabel">Theme Customizer</h5>
			<button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas"></button>
		</div>
		<div class="offcanvas-body">
			<h6 class="mb-0">Theme Variation</h6>
			<hr>
			<div class="form-check form-check-inline">
				<input class="form-check-input" type="radio" name="inlineRadioOptions" id="lightmode" value="option1" checked>
				<label class="form-check-label" for="lightmode">Light</label>
			</div>
			<hr>
			<div class="form-check form-check-inline">
				<input class="form-check-input" type="radio" name="inlineRadioOptions" id="darkmode" value="option2">
				<label class="form-check-label" for="darkmode">Dark</label>
			</div>
			<hr>
			<div class="form-check form-check-inline">
				<input class="form-check-input" type="radio" name="inlineRadioOptions" id="darksidebar" value="option3">
				<label class="form-check-label" for="darksidebar">Semi Dark</label>
			</div>
			<hr>
			<div class="form-check form-check-inline">
				<input class="form-check-input" type="radio" name="inlineRadioOptions" id="ColorLessIcons" value="option3">
				<label class="form-check-label" for="ColorLessIcons">Color Less Icons</label>
			</div>
		</div>
	</div>
</div>
<!--end switcher-->