routes/web.php
<?php

use App\Models\IssuePackage;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StockController;
use App\Http\Controllers\Admin\CityController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\DonarController;
use App\Http\Controllers\IssuePackageController;
use App\Http\Controllers\Admin\DpersonController;
use App\Http\Controllers\Admin\PackageController;
use App\Http\Controllers\Admin\InventoryController;
use App\Http\Controllers\Admin\AssignPackageController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::get('/', function () {
    return redirect()->route('login');
});

Route::get('/login', function () {
    return view('auth.login');
})->name('login');
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Auth::routes();

Route::group(['prefix' => 'admin', 'as' => 'admin.'], function () {

    Route::middleware(['auth',])->group(function () {



        //Admin Routes
        Route::get('dashboard', [AdminController::class, 'AdminDashboard']);

        //DRP's Routes
        Route::get('dperson', [DpersonController::class, 'index']);
        Route::get('add/person', [DpersonController::class, 'create']);
        Route::post('store/person', [DpersonController::class, 'store']);
        Route::get('edit/person/{id}', [DpersonController::class, 'edit']);
        Route::put('update/person/{id}', [DpersonController::class, 'update']);
        Route::get('delete/person/{id}', [DpersonController::class, 'destroy']);

        // Packages routes

        Route::get('package', [PackageController::class, 'index']);
        Route::get('add/package', [PackageController::class, 'create']);
        Route::post('store/package', [PackageController::class, 'store']);
        Route::get('edit/package/{id}', [PackageController::class, 'edit']);
        Route::put('update/package/{id}', [PackageController::class, 'update']);
        Route::get('delete/package/{id}', [PackageController::class, 'destroy']);

        // inventory routes

        Route::resource('product', InventoryController::class);
        Route::get('inventory-report', [InventoryController::class,'inventory_report'])->name('product.inventory_report');

        // Donar routes

        Route::resource('donar', DonarController::class);
        Route::resource('user', DonarController::class);
        Route::get('delete-user/{id}', [DonarController::class,'destroy']);
        Route::get('delete-donor/{id}', [DonarController::class,'destroyDonor']);
        Route::get('donar-history/{id}', [DonarController::class,'donorHistory']);

        Route::post('store-donor', [DonarController::class,'storeDonor']);
        Route::get('donor-list', [DonarController::class,'donorall']);
        Route::get('donor-create', [DonarController::class,'createDonor']);
        Route::get('donor-edit/{id}', [DonarController::class,'editDonor']);
        Route::put('donar-update/{id}', [DonarController::class,'updateDonor']);
        Route::get('donar-history/{id}', [DonarController::class,'donorHistory']);
        Route::post('new-donation', [DonarController::class,'newDonation']);

       // cities route
       Route::get('/get-cities/{state}', [CityController::class, 'getCities']);
       // Roles
        Route::resource('role', RoleController::class);

        // Stock Management
        Route::resource('stock', StockController::class);



        // Assign packages
        Route::get('all-assign-package', [PackageController::class, 'allAssignPackage']);
        Route::post('assign-package', [PackageController::class, 'assignPackageNow']);
        Route::get('assign-package', [PackageController::class, 'assignPackage']);
        Route::get('get-package-detail', [PackageController::class, 'PackageDetails']);
        Route::get('edit-package-detail/{id}', [PackageController::class, 'editPackageDetails']);
        Route::get('edit-assign-package/{id}', [PackageController::class, 'editAssignPackage']);
        Route::put('update-assigned-package/{id}', [PackageController::class, 'updatePackageDetails']);
        Route::get('delete-assigned-package/{id}', [PackageController::class, 'destroyAssignedPackage']);

        // Issue Package
        Route::get('issue-package', [IssuePackageController::class, 'index']);
        Route::post('issue-now', [IssuePackageController::class, 'store']);
        Route::get('search-issue-people', [IssuePackageController::class, 'create']);
        Route::post('search-issue-people', [IssuePackageController::class, 'searchDPeople']);
        Route::get('issue-packages-report', [IssuePackageController::class, 'issuePackageReport']);
        Route::get('issued-package/{id}', [IssuePackageController::class, 'issuedPackage']);

        // Route::get('get-issuepkg/{slug}', IssuePackageController::class, 'getIssuePkg');

    });
            //Is Admin Middleware
    Route::middleware(['auth','isAdmin'])->group(function () {

        //UserListing
        Route::get('userlist',[AdminController::class, 'UsersListing']);
        Route::patch('updateStatus',[ AdminController::class,'updateUserStatus'])->name('userlist.updateUserstatus');
        Route::get('userlist/destroy/{id}',[AdminController::class, 'destroy']);

    });


});

app/Models/Stock.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Stock extends Model
{
    use HasFactory;

    public $guarded = [];




    public function product()
    {
        return $this->belongsTo(Product::class);
    }
    public function AddedBy()
    {
        return $this->belongsTo(User::class,'added_by','id');
    }
}

app/Http/Controllers/StockController.php
<?php

namespace App\Http\Controllers;

use App\Models\InventoryHistory;
use App\Models\Product;
use App\Models\Stock;
use Illuminate\Http\Request;

class StockController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $stocks = Stock::with(['AddedBy'])->get();
        return view('admin.stock.index', compact('stocks'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $products = Product::all();
        return view('admin.stock.create', compact('products'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {

        foreach ($request->data as $item) {
            Stock::create([
                'product_id' => $item['product_id'],
                'qty' => $item['qty'],
                'added_by'=>auth()->id()
            ]);
            Product::where('id', $item['product_id'])->increment('qty',$item['qty']);
            InventoryHistory::create([
                'product_id'=>$item['product_id'],
                'qty'=>$item['qty'],
                'type'=>'add',
                'description'=>'Stock Added by '.auth()->user()->first_name
            ]);
        }
        return redirect(route('admin.stock.index'))->with(['success'=>'Stock Added Successfully']);

    }

    /**
     * Display the specified resource.
     */
    public function show(Stock $stock)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Stock $stock)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Stock $stock)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Stock $stock)
    {
        //
    }
}

resources/views/admin/stock/create.blade.php
@extends('layouts.admin')
<style>
    .container {
        margin-top: 80px;
        margin-left: 20%;
        /* margin-left: 10%; */
    }

    .col-md-10 {
        margin-left: 10%;
    }
</style>
@section('content')
    <!--page-wrapper-->
    <div class="page-wrapper">
        <!--page-content-wrapper-->
        <div class="page-content-wrapper">
            <div class="page-content">
                <!--breadcrumb-->
                <div class="page-breadcrumb d-none d-sm-flex align-items-center mb-3">
                    <div class="breadcrumb-title pe-3">Add New Stock</div>
                    
                    <div class="ms-auto">
                        <div class="btn-group">
                            <a href="{{ url('admin/package') }}" class="btn btn-primary">Back</a>
                        </div>
                    </div>
                </div>
                <!--end breadcrumb-->
                <div class="row bg-white">
                    <form action="{{ route('admin.stock.store') }}" method="POST">
                        @csrf
                        <div id="box" >
                            <div class="row">
                                <div class="col-xs-4 col-sm-4 col-md-4 mt-2">
                                    <strong>Product Name:</strong>
                                    <select name="data[0][product_id]" id="productName" class="form-control" required>
                                        <option value="">Select Product</option>

                                        @foreach ($products as $product)
                                            <option value="{{ $product->id }}">{{ strtoupper($product->product_name ) }} - unit - {{ $product->unit }}</option>
                                        @endforeach
                                    </select>
                                </div>
                                <div class="col-xs-3 col-sm-3 col-md-3 mt-2">

                                    <strong>Quantity:</strong>
                                    <input type="number" class="form-control" name="data[0][qty]" />
                                </div>

                                <div class=" col-sm-2 col-md-2 mt-2">
                                    <button type="submit" id="addProduct" class="btn btn-primary mt-3 ">Add</button>

                                </div>

                            </div>

                        </div>

                        <div class=" col-sm-12 col-md-12 text-end">
                            <button type="submit" class="btn btn-primary mt-2">Submit</button>
                        </div>
                    </form>
                </div>
                <!--end row-->
            </div>
        </div>
        <!--end page-content-wrapper-->
    </div>
    <!--end page-wrapper-->
@endsection

@push('scripts')

<script>
    $(document).ready(function() {
        $("#addProduct").on("click", function(e) {
            e.preventDefault();
            var element = document.getElementById("box");
            var numberOfChildren = element.children.length;

            let index = numberOfChildren;
            var newTask = `
            <div class="row">
            <div class="col-xs-4 col-sm-4 col-md-4 mt-2">
                                <strong>Product Name:</strong>
                                <select name="data[${index}][product_id]" id="productName" class="form-control" required>
                                    <option value="">Select Product</option>

                                    @foreach ($products as $product)
                                        <option value="{{ $product->id }}">{{ $product->product_name }} - unit - {{ $product->unit }}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="col-xs-3 col-sm-3 col-md-3 mt-2">
                                <strong>Quantity:</strong>
                                <input type="number" class="form-control" name="data[${index}][qty]" />
                            </div>

                            <div class=" col-sm-2 col-md-2 mt-2">
                                <button type="submit" id="remove_row" class="btn btn-danger btn-sm mt-3 ">Remove</button>

                            </div>

                        </div>
                `;
            $("#box").append(newTask);


        });


        $(document).on("click", "#remove_row", function() {

            $(this).closest(".row").remove();
        })

    });
</script>
@endpush

resources/views/admin/stock/index.blade.php
@extends('layouts.admin')

@section('content')
    <style>
        .card {
            margin-top: 80px;
            margin: 10px;
        }
    </style>

    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/buttons/2.4.1/css/buttons.dataTables.min.css">
    <!--page-wrapper-->
    <div class="page-wrapper">
        <!--page-content-wrapper-->
        <div class="page-content-wrapper">
            <div class="col-md-12">

                <div class="card">
                    <div class="card-header d-flex justify-content-between">
                        <h4>Inventory Stock History</h4>
                    </div>

                    <div class="card-body">
                    <div class="table-responsive">
							<table id="example2" class="table table-striped table-bordered" style="width:100%">

                            <thead>
                                <th>ID</th>
                                <th>Name</th>
                                <th>Qty</th>
                                <th>Added On</th>
                                <th>Added By</th>
                            </thead>

                            <tbody>

                                @forelse ($stocks as $product)
                                    <tr>
                                        <td>{{ $product->id }}</td>
                                        <td>{{ @$product->product->product_name }}</td>
                                        <td>{{ $product->qty }}</td>
                                        <td>{{ $product->created_at }}</td>
                                        <td>{{ @$product->AddedBy->first_name.' '.  @$product->AddedBy->last_name}}</td>
                                    </tr>
                                @empty
                                    <tr>
                                        <td colspan="5">No Date Found</td>
                                    </tr>
                                @endforelse
                            </tbody>
                        </table>
                    </div> </div>
                </div>
            </div>
        </div>
    </div>
@endsection